// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//同步玩家ID
type SyncPid struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPid) Reset()         { *m = SyncPid{} }
func (m *SyncPid) String() string { return proto.CompactTextString(m) }
func (*SyncPid) ProtoMessage()    {}
func (*SyncPid) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *SyncPid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPid.Unmarshal(m, b)
}
func (m *SyncPid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPid.Marshal(b, m, deterministic)
}
func (m *SyncPid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPid.Merge(m, src)
}
func (m *SyncPid) XXX_Size() int {
	return xxx_messageInfo_SyncPid.Size(m)
}
func (m *SyncPid) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPid.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPid proto.InternalMessageInfo

func (m *SyncPid) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

//位置信息
type Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	V                    float32  `protobuf:"fixed32,4,opt,name=V,proto3" json:"V,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

//广播消息
type BroadCase struct {
	Pid int32 `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Tp  int32 `protobuf:"varint,2,opt,name=Tp,proto3" json:"Tp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCase_Content
	//	*BroadCase_P
	//	*BroadCase_ActionData
	Data                 isBroadCase_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadCase) Reset()         { *m = BroadCase{} }
func (m *BroadCase) String() string { return proto.CompactTextString(m) }
func (*BroadCase) ProtoMessage()    {}
func (*BroadCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *BroadCase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCase.Unmarshal(m, b)
}
func (m *BroadCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCase.Marshal(b, m, deterministic)
}
func (m *BroadCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCase.Merge(m, src)
}
func (m *BroadCase) XXX_Size() int {
	return xxx_messageInfo_BroadCase.Size(m)
}
func (m *BroadCase) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCase.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCase proto.InternalMessageInfo

func (m *BroadCase) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *BroadCase) GetTp() int32 {
	if m != nil {
		return m.Tp
	}
	return 0
}

type isBroadCase_Data interface {
	isBroadCase_Data()
}

type BroadCase_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,proto3,oneof"`
}

type BroadCase_P struct {
	P *Position `protobuf:"bytes,4,opt,name=P,proto3,oneof"`
}

type BroadCase_ActionData struct {
	ActionData int32 `protobuf:"varint,5,opt,name=ActionData,proto3,oneof"`
}

func (*BroadCase_Content) isBroadCase_Data() {}

func (*BroadCase_P) isBroadCase_Data() {}

func (*BroadCase_ActionData) isBroadCase_Data() {}

func (m *BroadCase) GetData() isBroadCase_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCase) GetContent() string {
	if x, ok := m.GetData().(*BroadCase_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCase) GetP() *Position {
	if x, ok := m.GetData().(*BroadCase_P); ok {
		return x.P
	}
	return nil
}

func (m *BroadCase) GetActionData() int32 {
	if x, ok := m.GetData().(*BroadCase_ActionData); ok {
		return x.ActionData
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BroadCase) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BroadCase_Content)(nil),
		(*BroadCase_P)(nil),
		(*BroadCase_ActionData)(nil),
	}
}

func init() {
	proto.RegisterType((*SyncPid)(nil), "pb.SyncPid")
	proto.RegisterType((*Position)(nil), "pb.Position")
	proto.RegisterType((*BroadCase)(nil), "pb.BroadCase")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe6, 0x62, 0x0f, 0xae, 0xcc,
	0x4b, 0x0e, 0xc8, 0x4c, 0x11, 0x12, 0xe0, 0x62, 0x0e, 0xc8, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x02, 0x31, 0x95, 0x9c, 0xb8, 0x38, 0x02, 0xf2, 0x8b, 0x33, 0x4b, 0x32, 0xf3, 0xf3,
	0x84, 0x78, 0xb8, 0x18, 0x23, 0xc0, 0x72, 0x4c, 0x41, 0x8c, 0x11, 0x20, 0x5e, 0xa4, 0x04, 0x13,
	0x84, 0x17, 0x09, 0xe2, 0x45, 0x49, 0x30, 0x43, 0x78, 0x51, 0x20, 0x5e, 0x98, 0x04, 0x0b, 0x84,
	0x17, 0xa6, 0x34, 0x91, 0x91, 0x8b, 0xd3, 0xa9, 0x28, 0x3f, 0x31, 0xc5, 0x39, 0xb1, 0x38, 0x15,
	0xd3, 0x0e, 0x21, 0x3e, 0x2e, 0xa6, 0x90, 0x02, 0xb0, 0x51, 0xac, 0x41, 0x4c, 0x21, 0x05, 0x42,
	0x52, 0x5c, 0xec, 0xce, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x60, 0x13, 0x39, 0x3d, 0x18, 0x82,
	0x60, 0x02, 0x42, 0x32, 0x5c, 0x8c, 0x01, 0x60, 0x93, 0xb9, 0x8d, 0x78, 0xf4, 0x0a, 0x92, 0xf4,
	0x60, 0x8e, 0xf3, 0x60, 0x08, 0x62, 0x0c, 0x10, 0x52, 0xe0, 0xe2, 0x72, 0x4c, 0x06, 0x71, 0x5d,
	0x12, 0x4b, 0x12, 0x25, 0x58, 0x41, 0x26, 0x7a, 0x30, 0x04, 0x21, 0x89, 0x39, 0xb1, 0x71, 0xb1,
	0x80, 0x69, 0xd6, 0x55, 0x4c, 0x4c, 0x01, 0x49, 0x49, 0x6c, 0xe0, 0x60, 0x30, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0xfa, 0x96, 0x65, 0x13, 0x01, 0x00, 0x00,
}
